spring:
  application:
    name: gateway
  main:
    allow-circular-references: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: coa-api
          uri: lb://coa-api/
          predicates:
            - Path=/coa-api/**
          filters:
            - AuthFilter
        - id: get-coe
          uri: lb://coe
          predicates:
            - Path=/coe/**
          filters:
            - AuthFilter
            - name: CircuitBreaker
              args:
                name: CortoCircuito
                fallbackUri: forward:/error
        - id: auth-service
          uri: lb:/auth-service
          predicates:
            - Path=/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: CortoCircuito
                fallbackUri: forward:/error

server:
  port: 9070
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

uri:
  auth:
    validate: http://localhost:9070/AUTH-SERVICE/auth/validate