spring:
  application:
    name: gateway
#  main:
#    allow-circular-references: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: academica
          uri: lb://COA-SERVICE
          predicates:
            - Path=/coa-api/**
          filters:
            - AuthFilter
            - name: CircuitBreaker
              args:
                name: CortoCircuito
                fallbackUri: forward:/error
        - id: escolar
          uri: lb://COE-SERVICE
          predicates:
            - Path=/coe/**
          filters:
            - AuthFilter
            - name: CircuitBreaker
              args:
                name: CortoCircuito
                fallbackUri: forward:/error
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: CortoCircuito
                fallbackUri: forward:/error
        - id: test-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: CortoCircuito
                fallbackUri: forward:/error

server:
  port: 9070
  servlet:
    context-path: uady
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#    prefer-ip-address: true

uri:
  auth:
    validate: http://localhost:9070/AUTH-SERVICE/auth/validate