server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

security:
  keysecret: q1sAno98700c34Der

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
admin-paths:
   paths:
     - uri: "/coa-api/plan-estudios"
       method: "GET"
     - uri: "/coa-api/materias"
       method: "GET"
     - uri: "/coe/kardex"
       method: "GET"
     - uri: "/coe/alumno"
       method: "GET"